services:
  haos-converter:
    build: .
    container_name: haos-app-converter
    environment:
      - HAOS_DEBUG=true
    ports:
      - "8985:80"
    volumes:
      - .:/var/www/html
    restart: unless-stopped
